server:
  port: 8080

spring.data.mongodb:
  host: mongodb
  port: 27017
  database: myDB
  username: admin
  password: manager
  authenticationDatabase: admin

  redis:
    host: redis
    port: 6379

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false