server:
  port: 8080

spring.data.mongodb:
  host: mongo
  port: 27017
  database: myDB
  username: admin
  password: manager
  authenticationDatabase: admin

spring.redis:
  host: redis
  port: 6379

spring.jackson.serialization:
  WRITE_DATES_AS_TIMESTAMPS: false