version: '3.7'
services:
  app:
    build: .
    image: "examples/boot-redis-mongo"
    container_name: "boot-redis-mongo"
    volumes:
      - c:/var/docker/volumes/logs:/app/logs
    ports:
      - "8080:8080"
    environment:
      TZ: Canada/Eastern
    links:
      - mongo
      - redis

  mongo:
    image: "mongo"
    container_name: "mongo"
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

  redis:
    image: "redis"
    container_name: "redis"
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  mongodata:
    external: true
  redis-data:
    external: true
